### ISSUE TITLE
Sub-menu links do not navigate

### ISSUE THREAD

**Issue by OskarD** [sourcey/spectacle#15]
When I click an expanded sub-menu link, I expect to be navigated to that functionality. Nothing happens.

When the page is loaded, this JS error is printed multiple times in my console: 
`Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLAnchorElement.<anonymous> (http://localhost:4400/javascripts/spectacle.min.js:1:2089)
    at HTMLElement.dispatch (http://code.jquery.com/jquery-2.1.4.min.js:3:6466)
    at HTMLElement.r.handle (http://code.jquery.com/jquery-2.1.4.min.js:3:3241)`

Edit:
Also it appears my parameter description tag is not applied to the documentation:
``` 
      parameters:
      - name: "interestRate"
        in: "query"
        required: true
        type: "number"
        minimum: 0.0
        description: "Test"
``` 

It just says `(no description)`

I am using a yml file to generate the documentation, perhaps that has something to do with my problems?
