### ISSUE TITLE
Enums values for nested objects in a Swagger schema

### ISSUE THREAD

**Issue by regel** [sourcey/spectacle#193]
Enums values for nested objects in a Swagger schema are not visible in the HTML files produced by Spectacle.

Swagger schema example:

```
definitions:
  Addr:
    type: object
    properties:
      remarks:
        description: >-
          Additional remarks to return partial or exact match information
        type: object
        properties:
          street:
            description: >-
              Partial match information for street field
            type: string
            enum:
              - 'exact_match'
              - 'did not match exactly'
```

The valid enum values "exact_match" and "did not match exactly" are not documented in the HTML file.

Environment:

2019-10-18 latest Docker image:

```
Digest: sha256:d1b38c1c5d557fbf635d38cf2c1d847d759ea3d991c0f93d57ef64c0a098d0d8
Status: Downloaded newer image for sourcey/spectacle:latest
docker.io/sourcey/spectacle:latest
```
