### ISSUE TITLE
Parameter description is not showing

### ISSUE THREAD

**Issue by OskarD** [sourcey/spectacle#22]
I have a `swagger.yml` file that contains:
```
...
/some/endpoint:
    get:
      tags:
      - "My Tag"
      summary: "This is an endpoint"
      description: "It has an end on its point"
      operationId: "someEndpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "aParameter"
        description: "This is not printed"
        in: "query"
        required: true
        type: "integer"
        minimum: 1.0
        format: "int32"
...
```
When I look at the webpage, it says `(no description)`.

Am I doing something wrong?
