### ISSUE TITLE
Missing helper: "json"

### ISSUE THREAD

**Issue by CodeLenny** [sourcey/spectacle#25]
Hi,
I've been getting an error when using an example in a definition.

```yml
definitions:
  MyObject:
    type: object
    properties:
      myprop:
        type: string
    example:
      myprop: sample property value
```

I get the following error:
```
Running "compile-handlebars:compile" (compile-handlebars) task
Task error: { [Error: Missing helper: "json"]
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: 'Missing helper: "json"',
  name: 'Error',
  number: undefined }
```

I tried adding a JSON handler (https://github.com/CodeLenny/spectacle/tree/json-handler), which stopped the above error and compiled my API docs, but included my example on the left.  I expected it to appear on the right, like other examples do, and be syntax highlighted/monospace.

![spectacle-example](https://cloud.githubusercontent.com/assets/9272847/21360223/fa01e23e-c6ac-11e6-9a55-6f514656e094.png)

Is this intended?
