### ISSUE TITLE
produces/consumes from paths: is not shown

### ISSUE THREAD

**Issue by lunemec** [sourcey/spectacle#64]
Path produces/consumes MIME type's are not displayed anywhere on the rendered page:
Example:
```yml
paths:
  /endpoint/v1:
    post:
      tags:
      - "my_endpoint"
      summary: "summary"
      description: "desc"
      consumes:
      - "application/json"
      produces:
      - "application/json"
```

The `application/json` is not shown in the rendered docs.
Thx!
