### ISSUE TITLE
Show defaults for parameters

### ISSUE THREAD

**Issue by liamdennehy** [sourcey/spectacle#72]
When a parameter is not required, the default value is rather important, but is not shown in the rendered specification. Hopefully this is trivial to add, but my JS foo is nonexistent so I can't do this myself.
```
paths:
  /orders:
    get:
      summary: 'List orders'
      parameters:
      - name: OnlyOpen
        in: header
        type: boolean
        description: Only return open orders?
        default: true
```
