### ISSUE TITLE
replaceRefs fails when attributes have null values

### ISSUE THREAD

**Issue by glb** [sourcey/spectacle#96]
I have a spec that may or may not be correct; it looks (in part) like this:
```
      parameters:
        - name: sample
          in: query
          type: string
          default:
          description: |
            Sample parameter that exhibits the issue.
```
When `spectacle` encounters the `default` key in this object, it dies, saying:
```
TypeError: Cannot read property '$ref' of null
```
There is a check in `replaceRefs` that says:
```
if(typeof val !== "object") { continue; }
```
but unfortunately `typeof(null) === "object"```, so the key isn't skipped and spectacle crashes.

The fix is to add a null check as well; PR is on its way.
