### ISSUE TITLE
objects within definitions are not shown properly in the docs

### ISSUE THREAD

**Issue by lea-anthony** [sourcey/spectacle#98]
Problem:
When a definition has a property that is an object, this property is shown as "object" with none of its own properties outputted to the doc.

Example doc fragment:
```
...
      challenges:
        type: object
        properties:
          total:
            description: Total number of challenges
            type: integer
          completed:
            description: Number of challenges completed by participant
            type: integer
...
```
Renders to:
challenges: object

Expected behaviour:

Sub-properties to be documented also.
